/*

*/

export const SHOP_DATA_MEN = [
  {
    title: "Hoodies",
    id: 1,
    items: [
      {
        id: 104,
        name: "Magenta Striped Overshirt",
        imageUrl: "/product-images/men/hoodies/hoodie1.jpg",
        price: 49.95,
        color: "red pink",
      },
      {
        id: 105,
        name: "Green Oversized Shirt",
        imageUrl: "/product-images/men/hoodies/hoodie2.jpg",
        price: 59.95,
        color: "green",
      },
      {
        id: 106,
        name: "Black Northface Fleece",
        imageUrl: "/product-images/men/hoodies/hoodie3.jpg",
        price: 79.95,
        color: "black",
      },
      {
        id: 107,
        name: "White Hoodie Boss",
        imageUrl: "/product-images/men/hoodies/hoodie4.jpg",
        price: 49.95,
        color: "white",
      },
      {
        id: 108,
        name: "Some Black Hoodie",
        imageUrl: "/product-images/men/hoodies/hoodie5.jpg",
        price: 47.95,
        color: "black",
      },
      {
        id: 109,
        name: "Another Black Pullover",
        imageUrl: "/product-images/men/hoodies/hoodie6.jpg",
        price: 89.95,
        color: "black",
      },
      {
        id: 110,
        name: "Olivegreen Pullover",
        imageUrl: "/product-images/men/hoodies/hoodie7.jpg",
        price: 69.95,
        color: "green",
      },
      {
        id: 111,
        name: "Blue Barbour Sweatshirt",
        imageUrl: "/product-images/men/hoodies/hoodie8.jpg",
        price: 59.95,
        color: "blue",
      },
      {
        id: 112,
        name: "Gray Sweatshirt",
        imageUrl: "/product-images/men/hoodies/hoodie9.jpg",
        price: 65.95,
        color: "gray",
      },
      {
        id: 113,
        name: "Yellowish Hoodie",
        imageUrl: "/product-images/men/hoodies/hoodie10.jpg",
        price: 79.95,
        color: "yellow",
      },
      {
        id: 114,
        name: "Blue Thing",
        imageUrl: "/product-images/men/hoodies/hoodie11.jpg",
        price: 69.95,
        color: "blue",
      },
      {
        id: 115,
        name: "Pink Hoodie",
        imageUrl: "/product-images/men/hoodies/hoodie12.jpg",
        price: 55.95,
        color: "pink",
      },
    ],
  },
  {
    title: "Shoes",
    id: 2,
    items: [
      {
        id: 116,
        name: "White N Shoes",
        imageUrl: "/product-images/men/shoes/shoes1.jpg",
        price: 49.95,
        color: "white",
      },
      {
        id: 117,
        name: "Green N Shoes",
        imageUrl: "/product-images/men/shoes/shoes2.jpg",
        price: 59.95,
        color: "green",
      },
      {
        id: 118,
        name: "Gray Shoes",
        imageUrl: "/product-images/men/shoes/shoes3.jpg",
        price: 79.95,
        color: "gray",
      },
      {
        id: 119,
        name: "Some Black Shoes",
        imageUrl: "/product-images/men/shoes/shoes4.jpg",
        price: 49.95,
        color: "black",
      },
      {
        id: 120,
        name: "Some White Shoes",
        imageUrl: "/product-images/men/shoes/shoes5.jpg",
        price: 47.95,
        color: "white",
      },
      {
        id: 121,
        name: "Black & White Nike Shoes",
        imageUrl: "/product-images/men/shoes/shoes6.jpg",
        price: 89.95,
        color: "black white",
      },
      {
        id: 122,
        name: "Nike Sport Shoes",
        imageUrl: "/product-images/men/shoes/shoes7.jpg",
        price: 69.95,
        color: "black",
      },
      {
        id: 123,
        name: "Greenish Shoes",
        imageUrl: "/product-images/men/shoes/shoes8.jpg",
        price: 59.95,
        color: "green",
      },
      {
        id: 124,
        name: "White Polo Shoes",
        imageUrl: "/product-images/men/shoes/shoes9.jpg",
        price: 65.95,
        color: "white",
      },
      {
        id: 125,
        name: "Black Polo Shoes",
        imageUrl: "/product-images/men/shoes/shoes10.jpg",
        price: 79.95,
        color: "black",
      },
    ],
  },
  {
    title: "Accessories",
    id: 3,
    items: [
      {
        id: 126,
        name: "Some Watch",
        imageUrl: "/product-images/men/accessories/accessoire1.jpg",
        price: 49.95,
        color: "gray",
      },
      {
        id: 127,
        name: "Some Beanie",
        imageUrl: "/product-images/men/accessories/accessoire2.jpg",
        price: 59.95,
        color: "black",
      },
      {
        id: 128,
        name: "Gray Beanie",
        imageUrl: "/product-images/men/accessories/accessoire3.jpg",
        price: 79.95,
        color: "gray",
      },
      {
        id: 129,
        name: "Black Gloves",
        imageUrl: "/product-images/men/accessories/accessoire4.jpg",
        price: 49.95,
        color: "black",
      },
      {
        id: 130,
        name: "Barbour Bag",
        imageUrl: "/product-images/men/accessories/accessoire5.jpg",
        price: 47.95,
        color: "black",
      },
      {
        id: 131,
        name: "Another Beanie",
        imageUrl: "/product-images/men/accessories/accessoire6.jpg",
        price: 89.95,
        color: "red",
      },
      {
        id: 132,
        name: "Another bag",
        imageUrl: "/product-images/men/accessories/accessoire7.jpg",
        price: 69.95,
        color: "green",
      },
      {
        id: 133,
        name: "An orange Beanie",
        imageUrl: "/product-images/men/accessories/accessoire8.jpg",
        price: 59.95,
        color: "orange",
      },
      {
        id: 134,
        name: "Tommy Hilfiger Beanie",
        imageUrl: "/product-images/men/accessories/accessoire9.jpg",
        price: 65.95,
        color: "blue",
      },
      {
        id: 135,
        name: "Another watch",
        imageUrl: "/product-images/men/accessories/accessoire10.jpg",
        price: 79.95,
        color: "white",
      },
    ],
  },
];


//////////////////////////////////////////////////////////


export const SHOP_DATA_WOMEN = [
  {
    title: "Dresses",
    id: 1,
    items: [
      {
        id: 1,
        name: "Green Floral Satin Dress",
        imageUrl: "/product-images/women/dresses/dress1.jpg",
        price: 49.95,
        color: "green",
      },
      {
        id: 2,
        name: "Classic Black Dress",
        imageUrl: "/product-images/women/dresses/dress2.jpg",
        price: 59.95,
        color: "black",
      },
      {
        id: 3,
        name: "Black Short Dress With Print",
        imageUrl: "/product-images/women/dresses/dress3.jpg",
        price: 79.95,
        color: "black",
      },
      {
        id: 4,
        name: "Green Blue Cotton Dress",
        imageUrl: "/product-images/women/dresses/dress4.jpg",
        price: 49.95,
        color: "green",
      },
      {
        id: 5,
        name: "Red Sommer Dress",
        imageUrl: "/product-images/women/dresses/dress5.jpg",
        price: 47.95,
        color: "red",
      },
      {
        id: 6,
        name: "Another Black Dress",
        imageUrl: "/product-images/women/dresses/dress6.jpg",
        price: 89.95,
        color: "black",
      },
      {
        id: 7,
        name: "Classic Green Black Dress",
        imageUrl: "/product-images/women/dresses/dress7.jpg",
        price: 69.95,
        color: "green",
      },
      {
        id: 8,
        name: "Light Summer Dress White",
        imageUrl: "/product-images/women/dresses/dress8.jpg",
        price: 59.95,
        color: "white ",
      },
      {
        id: 9,
        name: "Black Dress",
        imageUrl: "/product-images/women/dresses/dress9.jpg",
        price: 65.95,
        color: "black",
      },
      {
        id: 10,
        name: "Blue Floral Dress",
        imageUrl: "/product-images/women/dresses/dress10.jpg",
        price: 79.95,
        color: "blue",
      },
      {
        id: 11,
        name: "Pink Dress",
        imageUrl: "/product-images/women/dresses/dress11.jpg",
        price: 69.95,
        color: "pink",
      },
      {
        id: 12,
        name: "White Lazy Dress",
        imageUrl: "/product-images/women/dresses/dress12.jpg",
        price: 55.95,
        color: "white",
      },
    ],
  },
  {
    title: "Tops",
    id: 2,
    items: [
      {
        id: 13,
        name: "Black Top",
        imageUrl: "/product-images/women/tops/top1.jpg",
        price: 29.95,
        color: "black",
      },
      {
        id: 14,
        name: "White Shirt",
        imageUrl: "/product-images/women/tops/top2.jpg",
        price: 19.95,
        color: "white",
      },
      {
        id: 15,
        name: "Some Other Top",
        imageUrl: "/product-images/women/tops/top3.jpg",
        price: 39.95,
        color: "beige",
      },
      {
        id: 16,
        name: "Blue Or Purple Top",
        imageUrl: "/product-images/women/tops/top4.jpg",
        price: 17.95,
        color: "purple",
      },
      {
        id: 17,
        name: "Some More White Top",
        imageUrl: "/product-images/women/tops/top5.jpg",
        price: 25.95,
        color: "white",
      },
      {
        id: 18,
        name: "Brown Top",
        imageUrl: "/product-images/women/tops/top6.jpg",
        price: 35.95,
        color: "brown",
      },
      {
        id: 19,
        name: "Yet Another Black Top",
        imageUrl: "/product-images/women/tops/top7.jpg",
        price: 29.95,
        color: "black",
      },
      {
        id: 20,
        name: "Green T-Shirt",
        imageUrl: "/product-images/women/tops/top8.jpg",
        price: 49.95,
        color: "green",
      },
      {
        id: 21,
        name: "Red Long Shirt",
        imageUrl: "/product-images/women/tops/top9.jpg",
        price: 39.95,
        color: "red",
      },
      {
        id: 22,
        name: "Striped Shirt",
        imageUrl: "/product-images/women/tops/top10.jpg",
        price: 45.95,
        color: "red",
      },
      {
        id: 23,
        name: "Green Oversize Shirt",
        imageUrl: "/product-images/women/tops/top11.jpg",
        price: 27.95,
        color: "green",
      },
      {
        id: 24,
        name: "Striped Shirt",
        imageUrl: "/product-images/women/tops/top12.jpg",
        price: 39.95,
        color: "black white",
      },
    ],
  },
  {
    title: "Blazers",
    id: 3,
    items: [
      {
        id: 25,
        name: "Blue Oversize Blazer",
        imageUrl: "/product-images/women/blazers/blazer1.jpg",
        price: 75.95,
        color: "blue",
      },
      {
        id: 26,
        name: "Some Blazer",
        imageUrl: "/product-images/women/blazers/blazer2.jpg",
        price: 65.95,
        color: "brown",
      },
      {
        id: 27,
        name: "Pink Or Orange Suit",
        imageUrl: "/product-images/women/blazers/blazer3.jpg",
        price: 85.95,
        color: "pink",
      },
      {
        id: 28,
        name: "Black Blazer",
        imageUrl: "/product-images/women/blazers/blazer4.jpg",
        price: 55.95,
        color: "black",
      },
      {
        id: 29,
        name: "Another Pink Blazer",
        imageUrl: "/product-images/women/blazers/blazer5.jpg",
        price: 60.95,
        color: "pink",
      },
      {
        id: 30,
        name: "Light Summer Blazer",
        imageUrl: "/product-images/women/blazers/blazer6.jpg",
        price: 79.95,
        color: "beige",
      },
      {
        id: 31,
        name: "White Blazer",
        imageUrl: "/product-images/women/blazers/blazer7.jpg",
        price: 89.95,
        color: "white",
      },
      {
        id: 32,
        name: "Another Black Blazer",
        imageUrl: "/product-images/women/blazers/blazer8.jpg",
        price: 65.95,
        color: "black",
      },
      {
        id: 33,
        name: "Yet Another Black Blazer",
        imageUrl: "/product-images/women/blazers/blazer9.jpg",
        price: 64.95,
        color: "black",
      },
      {
        id: 34,
        name: "Some Beige Blazer",
        imageUrl: "/product-images/women/blazers/blazer10.jpg",
        price: 64.95,
        color: "white",
      },
      {
        id: 35,
        name: "Light Pink Blazer",
        imageUrl: "/product-images/women/blazers/blazer11.jpg",
        price: 74.95,
        color: "pink",
      },
      {
        id: 36,
        name: "Olive Greenish Blazer",
        imageUrl: "/product-images/women/blazers/blazer12.jpg",
        price: 59.95,
        color: "green",
      },
    ],
  },
  {
    title: "Hoodies & Sweatshirts",
    id: 4,
    items: [
      {
        id: 37,
        name: "Mineral Pink Teddy Jacket",
        imageUrl: "/product-images/women/hoodies/hoodie1.jpg",
        price: 39.95,
        color: "pink",
      },
      {
        id: 38,
        name: "Vans Pullover Black",
        imageUrl: "/product-images/women/hoodies/hoodie2.jpg",
        price: 49.95,
        color: "black",
      },
      {
        id: 39,
        name: "No Brand Top Black",
        imageUrl: "/product-images/women/hoodies/hoodie3.jpg",
        price: 29.95,
        color: "black",
      },
      {
        id: 40,
        name: "Beige Sweatshirt",
        imageUrl: "/product-images/women/hoodies/hoodie4.jpg",
        price: 59.95,
        color: "white",
      },
      {
        id: 41,
        name: "Green USA Pullover",
        imageUrl: "/product-images/women/hoodies/hoodie5.jpg",
        price: 25.95,
        color: "green",
      },
      {
        id: 42,
        name: "Brownish Pullover",
        imageUrl: "/product-images/women/hoodies/hoodie6.jpg",
        price: 69.95,
        color: "brown",
      },
      {
        id: 43,
        name: "Light Green Hoodie",
        imageUrl: "/product-images/women/hoodies/hoodie7.jpg",
        price: 45.95,
        color: "green",
      },
      {
        id: 44,
        name: "Today Is A Good Day",
        imageUrl: "/product-images/women/hoodies/hoodie8.jpg",
        price: 59.95,
        color: "blue",
      },
      {
        id: 45,
        name: "White Top without Print",
        imageUrl: "/product-images/women/hoodies/hoodie9.jpg",
        price: 49.95,
        color: "white",
      },
      {
        id: 46,
        name: "Not Yet Invented Color Hoodie",
        imageUrl: "/product-images/women/hoodies/hoodie10.jpg",
        price: 35.95,
        color: "unknown",
      },
      {
        id: 47,
        name: "Cozy Sweatshirt In Green",
        imageUrl: "/product-images/women/hoodies/hoodie11.jpg",
        price: 54.95,
        color: "green",
      },
      {
        id: 48,
        name: "Santa Monica Red Sweatshirt",
        imageUrl: "/product-images/women/hoodies/hoodie12.jpg",
        price: 54.95,
        color: "red",
      },
    ],
  },
  {
    title: "Shorts",
    id: 5,
    items: [
      {
        id: 49,
        name: "Black Shorts",
        imageUrl: "/product-images/women/shorts/short1.jpg",
        price: 29.95,
        color: "black",
      },
      {
        id: 50,
        name: "Puma Sport Shorts",
        imageUrl: "/product-images/women/shorts/short2.jpg",
        price: 25.95,
        color: "black",
      },
      {
        id: 51,
        name: "Mini Jeans",
        imageUrl: "/product-images/women/shorts/short3.jpg",
        price: 39.95,
        color: "blue",
      },
      {
        id: 52,
        name: "Asos Shorts Black",
        imageUrl: "/product-images/women/shorts/short4.jpg",
        price: 35.95,
        color: "black",
      },
      {
        id: 53,
        name: "Pink Mini Trousers",
        imageUrl: "/product-images/women/shorts/short5.jpg",
        price: 19.95,
        color: "pink",
      },
      {
        id: 54,
        name: "Some White Shorts",
        imageUrl: "/product-images/women/shorts/short6.jpg",
        price: 49.95,
        color: "white",
      },
      {
        id: 55,
        name: "Jeans Shorts",
        imageUrl: "/product-images/women/shorts/short7.jpg",
        price: 45.95,
        color: "blue",
      },
      {
        id: 56,
        name: "Light Green Shorts",
        imageUrl: "/product-images/women/shorts/short8.jpg",
        price: 37.95,
        color: "green",
      },
      {
        id: 57,
        name: "Tight Red Sport Shorts",
        imageUrl: "/product-images/women/shorts/short9.jpg",
        price: 37.95,
        color: "red",
      },
      {
        id: 58,
        name: "White Shorts 2",
        imageUrl: "/product-images/women/shorts/short10.jpg",
        price: 35.95,
        color: "white",
      },
    ],
  },
  {
    title: "Jeans",
    id: 6,
    items: [
      {
        id: 59,
        name: "Black Wide Jeans",
        imageUrl: "/product-images/women/jeans/jeans1.jpg",
        price: 49.95,
        color: "black",
      },
      {
        id: 60,
        name: "80s Blue Jeans",
        imageUrl: "/product-images/women/jeans/jeans2.jpg",
        price: 59.95,
        color: "blue",
      },
      {
        id: 61,
        name: "Casual Black Jeans",
        imageUrl: "/product-images/women/jeans/jeans3.jpg",
        price: 39.95,
        color: "black",
      },
      {
        id: 62,
        name: "Some Black Jeans",
        imageUrl: "/product-images/women/jeans/jeans4.jpg",
        price: 59.95,
        color: "black",
      },
      {
        id: 63,
        name: "Some more Blue Jeans",
        imageUrl: "/product-images/women/jeans/jeans5.jpg",
        price: 69.95,
        color: "blue",
      },
      {
        id: 64,
        name: "Wide Black Trousers",
        imageUrl: "/product-images/women/jeans/jeans6.jpg",
        price: 39.95,
        color: "black",
      },
      {
        id: 65,
        name: "Washed Out Light Jeans",
        imageUrl: "/product-images/women/jeans/jeans7.jpg",
        price: 39.95,
        color: "blue",
      },
      {
        id: 66,
        name: "Blue Jeans 2",
        imageUrl: "/product-images/women/jeans/jeans8.jpg",
        price: 49.95,
        color: "blue",
      },
      {
        id: 67,
        name: "Blue Jeans 3",
        imageUrl: "/product-images/women/jeans/jeans9.jpg",
        price: 45.95,
        color: "blue",
      },
      {
        id: 68,
        name: "Blue Jeans 4",
        imageUrl: "/product-images/women/jeans/jeans10.jpg",
        price: 48.95,
        color: "blue",
      },
      {
        id: 69,
        name: "More Blue Jeans",
        imageUrl: "/product-images/women/jeans/jeans11.jpg",
        price: 69.95,
        color: "blue",
      },
      {
        id: 70,
        name: "Wide Black Jeans 80s",
        imageUrl: "/product-images/women/jeans/jeans12.jpg",
        price: 79.95,
        color: "black",
      },
    ],
  },
  {
    title: "Shoes",
    id: 7,
    items: [
      {
        id: 71,
        name: "Black Converse",
        imageUrl: "/product-images/women/shoes/shoes1.jpg",
        price: 69.95,
        color: "black",
      },
      {
        id: 72,
        name: "White N Shoes ",
        imageUrl: "/product-images/women/shoes/shoes2.jpg",
        price: 59.95,
        color: "white",
      },
      {
        id: 73,
        name: "Some Black Shoes",
        imageUrl: "/product-images/women/shoes/shoes3.jpg",
        price: 79.95,
        color: "black",
      },
      {
        id: 74,
        name: "Shoes To Wear At Home",
        imageUrl: "/product-images/women/shoes/shoes4.jpg",
        price: 14.95,
        color: "white",
      },
      {
        id: 75,
        name: "Adidas Shoes",
        imageUrl: "/product-images/women/shoes/shoes5.jpg",
        price: 45.95,
        color: "white",
      },
      {
        id: 76,
        name: "Some more Shoes",
        imageUrl: "/product-images/women/shoes/shoes6.jpg",
        price: 59.95,
        color: "orange",
      },
      {
        id: 77,
        name: "Light Blue Plastic Shoes",
        imageUrl: "/product-images/women/shoes/shoes7.jpg",
        price: 19.95,
        color: "blue",
      },
      {
        id: 78,
        name: "Black High Heels",
        imageUrl: "/product-images/women/shoes/shoes8.jpg",
        price: 49.95,
        color: "black",
      },
      {
        id: 79,
        name: "Brown Vans",
        imageUrl: "/product-images/women/shoes/shoes9.jpg",
        price: 49.95,
        color: "brown",
      },
      {
        id: 80,
        name: "Green High Heels",
        imageUrl: "/product-images/women/shoes/shoes10.jpg",
        price: 55.95,
        color: "green",
      },
      {
        id: 81,
        name: "Greenish Shoes",
        imageUrl: "/product-images/women/shoes/shoes11.jpg",
        price: 59.95,
        color: "green",
      },
    ],
  },
  {
    title: "Sleepwear",
    id: 8,
    items: [
      {
        id: 82,
        name: "Black Satin Sleepwear",
        imageUrl: "/product-images/women/sleepwear/sleep1.jpg",
        price: 49.95,
        color: "black",
      },
      {
        id: 83,
        name: "Light pink Dress",
        imageUrl: "/product-images/women/sleepwear/sleep2.jpg",
        price: 45.95,
        color: "pink",
      },
      {
        id: 84,
        name: "Grey Sleepwear",
        imageUrl: "/product-images/women/sleepwear/sleep3.jpg",
        price: 44.95,
        color: "gray",
      },
      {
        id: 85,
        name: "Some Green Pyjamas",
        imageUrl: "/product-images/women/sleepwear/sleep4.jpg",
        price: 59.95,
        color: "green",
      },
      {
        id: 86,
        name: "Black Sleepwear",
        imageUrl: "/product-images/women/sleepwear/sleep5.jpg",
        price: 24.95,
        color: "black",
      },
      {
        id: 87,
        name: "Greenish Teddy Pyjamas",
        imageUrl: "/product-images/women/sleepwear/sleep6.jpg",
        price: 35.95,
        color: "green",
      },
      {
        id: 88,
        name: "Blue Satin Sleepdress",
        imageUrl: "/product-images/women/sleepwear/sleep7.jpg",
        price: 49.95,
        color: "blue",
      },
      {
        id: 89,
        name: "Cherryred Sleepwear",
        imageUrl: "/product-images/women/sleepwear/sleep8.jpg",
        price: 54.95,
        color: "red",
      },
      {
        id: 90,
        name: "Orange Pyjamas",
        imageUrl: "/product-images/women/sleepwear/sleep9.jpg",
        price: 49.95,
        color: "orange",
      },
      {
        id: 91,
        name: "Pink Sleepwear",
        imageUrl: "/product-images/women/sleepwear/sleep10.jpg",
        price: 39.95,
        color: "pink",
      },
      {
        id: 92,
        name: "White Sleepwear",
        imageUrl: "/product-images/women/sleepwear/sleep11.jpg",
        price: 39.95,
        color: "white",
      },
      {
        id: 93,
        name: "Some More Black Sleepwear",
        imageUrl: "/product-images/women/sleepwear/sleep12.jpg",
        price: 39.95,
        color: "black",
      },
    ],
  },
  {
    title: "Accessories",
    id: 9,
    items: [
      {
        id: 94,
        name: "Blue Nike Bag",
        imageUrl: "/product-images/women/accessoires/accessoires1.jpg",
        price: 54.95,
        color: "blue",
      },
      {
        id: 95,
        name: "Red Cap",
        imageUrl: "/product-images/women/accessoires/accessoires2.jpg",
        price: 29.95,
        color: "red",
      },
      {
        id: 96,
        name: "Hair Stripe Black",
        imageUrl: "/product-images/women/accessoires/accessoires3.jpg",
        price: 14.95,
        color: "black",
      },
      {
        id: 97,
        name: "Orange Beanie",
        imageUrl: "/product-images/women/accessoires/accessoires4.jpg",
        price: 24.95,
        color: "orange",
      },
      {
        id: 98,
        name: "White Hat",
        imageUrl: "/product-images/women/accessoires/accessoires5.jpg",
        price: 19.95,
        color: "white",
      },
      {
        id: 99,
        name: "Black Bag",
        imageUrl: "/product-images/women/accessoires/accessoires6.jpg",
        price: 9.95,
        color: "black",
      },
      {
        id: 100,
        name: "Gray Cotton Scarf",
        imageUrl: "/product-images/women/accessoires/accessoires7.jpg",
        price: 29.95,
        color: "gray",
      },
      {
        id: 101,
        name: "Beige Scarf",
        imageUrl: "/product-images/women/accessoires/accessoires8.jpg",
        price: 39.95,
        color: "beige",
      },
      {
        id: 102,
        name: "Some Watch",
        imageUrl: "/product-images/women/accessoires/accessoires9.jpg",
        price: 139.95,
        color: "silver",
      },
      {
        id: 103,
        name: "Pink Beanie",
        imageUrl: "/product-images/women/accessoires/accessoires10.jpg",
        price: 24.95,
        color: "pink",
      },
    ],
  },
];
