export const PRODUCTS_ACTION_TYPES = {
  FETCH_AND_SET_PRODUCTS_START: "products/FETCH_AND_SET_PRODUCTS_START",
  FETCH_AND_SET_PRODUCTS_SUCCESS: "products/FETCH_AND_SET_PRODUCTS_SUCCESS",
  FETCH_AND_SET_PRODUCTS_ERROR: "products/FETCH_AND_SET_PRODUCTS_ERROR",
};
