export const PRODUCTS_ACTION_TYPES = {
  FETCH_PRODUCTS_START: "products/FETCH_PRODUCTS_START",
  FETCH_PRODUCTS_SUCCESS: "products/FETCH_PRODUCTS_SUCCESS",
  FETCH_PRODUCTS_ERROR: "products/FETCH_PRODUCTS_ERROR",
};
